steps:
  - label: ":checkered_flag: Checkout"
    command: "git checkout -f"

  - label: ":maven: Build"
    command: "mvn clean install"
    artifact_paths:
      - "target/*.jar"

  - label: ":test_tube: Test"
    command: "mvn test"

  - label: ":sonar: SonarQube Analysis"
    command: "mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}"

  - wait

  # Snapshot Build Step
  - label: ":package: Publish Snapshot"
    command: "mvn  -Dgpg.skip=true deploy -Psnapshot,standard"
    branches: "development"
    agents:
      queue: "java_build_queue"

  # Release Build Step
  - label: ":rocket: Deploy Release to Maven Central"
    command: "mvn deploy -Prelease -Dgpg.keyname=${GPG_KEYNAME} -Dgpg.passphrase=${GPG_PASSPHRASE} -Dgpg.secretKeyring=${GPG_SECRET_KEYRING}"
    branches: "main"
    agents:
      queue: "java_build_queue"
