steps:
  - label: ":maven: Build and Deploy"
    command:
      - sed -i 's/<version>ml-\(.*\)<\/version>/<version>\1<\/version>/g' pom.xml
      - export NVD_API_KEY=$(buildkite-agent secret get nvd_api_key)
      - mvn -Dgpg.skip=true clean deploy -Pstandard
    plugins:
      - test-collector#v1.0.0:
          files: "target/surefire-reports/*.xml"
          format: "junit"
    env:
      SONAR_TOKEN: "${SONAR_TOKEN}"
      BUILDKITE_ANALYTICS_TOKEN: "$(buildkite-agent secret get JmsSelectorBuildKiteAnalytics)"

    agents:
      queue: "java_build_queue"